<a href="https://colab.research.google.com/github/NaveenShetter1/deep-learning-notebooks/blob/main/bank_churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [91]:
dataset=pd.read_csv("/content/sample_data/Churn_Modelling.csv")

In [92]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [93]:
# here 1st rownumber, customerid, surname will be not helpfull for finding output, so we will remove those columns

In [94]:
x=dataset.iloc[:,3:-1]

In [95]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [96]:
y=dataset.iloc[:,-1]

In [44]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [45]:
# now we have categorical data like geography and gender

In [46]:
# now by using label encoder we are going to convert categorical data to numerical data

In [47]:
# gender column to numerical

In [97]:
x.iloc[:,2].head()

0    Female
1    Female
2    Female
3    Female
4    Female
Name: Gender, dtype: object

In [98]:
x.iloc[:,2].unique()

array(['Female', 'Male'], dtype=object)

In [99]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

x.iloc[:,2]=le.fit_transform(x.iloc[:,2])

In [100]:
x.iloc[:,2].unique()

array([0, 1], dtype=object)

In [101]:
x.head()

CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France      0   42       2       0.00              1   
1          608     Spain      0   41       1   83807.86              1   
2          502    France      0   42       8  159660.80              3   
3          699    France      0   39       1       0.00              2   
4          850     Spain      0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [102]:
x

CreditScore Geography Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France      0   42       2       0.00              1   
1             608     Spain      0   41       1   83807.86              1   
2             502    France      0   42       8  159660.80              3   
3             699    France      0   39       1       0.00              2   
4             850     Spain      0   43       2  125510.82              1   
...           ...       ...    ...  ...     ...        ...            ...   
9995          771    France      1   39       5       0.00              2   
9996          516    France      1   35      10   57369.61              1   
9997          709    France      0   36       7       0.00              1   
9998          772   Germany      1   42       3   75075.31              2   
9999          792    France      0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [103]:
# now to convert geography column from categorical to numerical

In [104]:
x.iloc[:,1]

0        France
1         Spain
2        France
3        France
4         Spain
         ...   
9995     France
9996     France
9997     France
9998    Germany
9999     France
Name: Geography, Length: 10000, dtype: object

In [105]:
x.iloc[:,1].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [106]:
# using one hot encoder

In [107]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [130]:
# all columns are filled with data

In [132]:
# now split the into train and test

In [133]:
from sklearn.model_selection import train_test_split
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=42)

In [134]:
# now here in deep learning feature scaling is very important

In [135]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
y_test=sc.transform(x_test)

In [136]:
x_train[0]

array([-1.02020406,  1.73668197, -0.56349184, -0.51250172,  0.90911166,
       -0.67729931, -0.69844549,  0.30084641,  0.80510537, -1.57810057,
       -1.0502616 , -0.99096946])

In [137]:
# now building our ANN

In [138]:
# adding 1st hidden layer

In [139]:
ann=tf.keras.models.Sequential()

In [140]:
# now here sequential is the architecture of layers under which we will be having types like dense, RNN ext, now adding 1st hidden layer using dense layer

In [141]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

In [142]:
# now adding 2nd hidden input layer

In [143]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

In [144]:
# now adding output layer

In [145]:
ann.add(tf.keras.layers.Dense(1, activation='sigmoid'))

# here activation is sigmoid because the output will be in binary either in 0 or 1
# if you the output is in multiclass than we will use activation as softmax

In [146]:
# dense means fully connected layer, here ANN means architecture

In [147]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [148]:
# here optimizer adam means it is using suckostic gd and here loss is binary_crossentropy because the activtion is binary means sigmoid
# we can give metrics multiple values under it

In [149]:
# training the ANN by training data

In [150]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.2462 - loss: 1.0629
Epoch 2/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.4207 - loss: 0.8087
Epoch 3/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.5747 - loss: 0.7139
Epoch 4/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7267 - loss: 0.6629
Epoch 5/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7846 - loss: 0.6397
Epoch 6/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8055 - loss: 0.6243
Epoch 7/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8137 - loss: 0.6092
Epoch 8/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7968 - loss: 0.5999
Epoch 9/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8149 - loss: 0.5868
Epoch 10/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8040 - loss: 0.5819
Epoch 11/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8206 - loss: 0.5629
Epoch 12/100
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy:

In [151]:
# predicting the result of a single observation

# use out ANN model to predict if the customer with following information will leave the bank:

# geography: France
# credit score: 600
# Gender: Male
# Age: 40 years old
# Tenure 3 years
# Balance: $60000

# Number of products: 2
# Does this customer have credit card: yes
# Is this customer is active member? yes
# estimated salary: $50000
# So, should we say good bye to the customer?


In [153]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step


array([[0.06581772]], dtype=float32)

In [155]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
[[0.06581772]]


In [156]:
# hence this is near to 0 so costomer will not exit

In [160]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[False]]
